/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WalletHistoryRouteImport } from './routes/wallet.history'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as ContestIdRouteImport } from './routes/contest.$id'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as AdminXpRouteImport } from './routes/admin.xp'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminLiveScoresRouteImport } from './routes/admin.live-scores'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContestsRouteImport } from './routes/admin.contests'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WalletHistoryRoute = WalletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WalletRoute,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIdRoute = ContestIdRouteImport.update({
  id: '/contest/$id',
  path: '/contest/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXpRoute = AdminXpRouteImport.update({
  id: '/xp',
  path: '/xp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveScoresRoute = AdminLiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsRoute = AdminContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-scores': typeof AdminLiveScoresRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/xp': typeof AdminXpRoute
  '/category/$id': typeof CategoryIdRoute
  '/contest/$id': typeof ContestIdRoute
  '/play/$id': typeof PlayIdRoute
  '/result/$id': typeof ResultIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-scores': typeof AdminLiveScoresRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/xp': typeof AdminXpRoute
  '/category/$id': typeof CategoryIdRoute
  '/contest/$id': typeof ContestIdRoute
  '/play/$id': typeof PlayIdRoute
  '/result/$id': typeof ResultIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contests': typeof AdminContestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-scores': typeof AdminLiveScoresRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/xp': typeof AdminXpRoute
  '/category/$id': typeof CategoryIdRoute
  '/contest/$id': typeof ContestIdRoute
  '/play/$id': typeof PlayIdRoute
  '/result/$id': typeof ResultIdRoute
  '/wallet/history': typeof WalletHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/events'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/live-scores'
    | '/login'
    | '/missions'
    | '/profile'
    | '/refer'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/contests'
    | '/admin/events'
    | '/admin/live-scores'
    | '/admin/missions'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/xp'
    | '/category/$id'
    | '/contest/$id'
    | '/play/$id'
    | '/result/$id'
    | '/wallet/history'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/books'
    | '/events'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/live-scores'
    | '/login'
    | '/missions'
    | '/profile'
    | '/refer'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/contests'
    | '/admin/events'
    | '/admin/live-scores'
    | '/admin/missions'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/xp'
    | '/category/$id'
    | '/contest/$id'
    | '/play/$id'
    | '/result/$id'
    | '/wallet/history'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/events'
    | '/hall-of-fame'
    | '/leaderboard'
    | '/live-scores'
    | '/login'
    | '/missions'
    | '/profile'
    | '/refer'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/contests'
    | '/admin/events'
    | '/admin/live-scores'
    | '/admin/missions'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/xp'
    | '/category/$id'
    | '/contest/$id'
    | '/play/$id'
    | '/result/$id'
    | '/wallet/history'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  EventsRoute: typeof EventsRoute
  HallOfFameRoute: typeof HallOfFameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveScoresRoute: typeof LiveScoresRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  ReferRoute: typeof ReferRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRouteWithChildren
  CategoryIdRoute: typeof CategoryIdRoute
  ContestIdRoute: typeof ContestIdRoute
  PlayIdRoute: typeof PlayIdRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wallet/history': {
      id: '/wallet/history'
      path: '/history'
      fullPath: '/wallet/history'
      preLoaderRoute: typeof WalletHistoryRouteImport
      parentRoute: typeof WalletRoute
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$id': {
      id: '/contest/$id'
      path: '/contest/$id'
      fullPath: '/contest/$id'
      preLoaderRoute: typeof ContestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/xp': {
      id: '/admin/xp'
      path: '/xp'
      fullPath: '/admin/xp'
      preLoaderRoute: typeof AdminXpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-scores': {
      id: '/admin/live-scores'
      path: '/live-scores'
      fullPath: '/admin/live-scores'
      preLoaderRoute: typeof AdminLiveScoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests': {
      id: '/admin/contests'
      path: '/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContestsRoute: typeof AdminContestsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLiveScoresRoute: typeof AdminLiveScoresRoute
  AdminMissionsRoute: typeof AdminMissionsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminXpRoute: typeof AdminXpRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContestsRoute: AdminContestsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLiveScoresRoute: AdminLiveScoresRoute,
  AdminMissionsRoute: AdminMissionsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminXpRoute: AdminXpRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WalletRouteChildren {
  WalletHistoryRoute: typeof WalletHistoryRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletHistoryRoute: WalletHistoryRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  EventsRoute: EventsRoute,
  HallOfFameRoute: HallOfFameRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveScoresRoute: LiveScoresRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  ReferRoute: ReferRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRouteWithChildren,
  CategoryIdRoute: CategoryIdRoute,
  ContestIdRoute: ContestIdRoute,
  PlayIdRoute: PlayIdRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
